export const TextureAliases = {
    "Building_DysonHabitat": "Building_Apartment",
    "Building_DysonHabitat2": "Building_Apartment",
    "Building_WirecardAG": "Building_MutualFund",
    "Building_NuclearArmsRace": "Building_NuclearMissileSilo",
    "Building_Caravansary2": "Building_Caravansary",
    "Building_Caravansary3": "Building_Caravansary",
    "Building_Caravansary4": "Building_Caravansary",
    "Building_Warehouse2": "Building_Warehouse",
    "Building_Warehouse3": "Building_Warehouse",
    "Building_Retreat1": "Building_House",
    "Building_Retreat2": "Building_Villa",
    "Building_PorcelainHut": "Building_Hut",
    "Building_ContainerHut": "Building_ContainerFactory",
    "Building_ZPMLab": "Building_SupercomputerLab",

    "Building_AlloyFactory": "Building_SteelMill",
    "Building_CompositeMaterialFactory": "Building_PlasticsFactory",
    "Building_ContainerPortRotterdam": "Building_ContainerPort",
    "Building_ContainerPortAntwerp": "Building_ContainerPort",
    "Building_ContainerPortHamburg": "Building_ContainerPort",
    "Building_ContainerPortValencia": "Building_ContainerPort",
    "Building_ContainerPortShanghai": "Building_ContainerPort",
    "Building_ContainerPortSingapore": "Building_ContainerPort",
    "Building_ContainerPortNingboZhoushan": "Building_ContainerPort",
    "Building_ContainerPortLosAngeles": "Building_ContainerPort",
    "Building_ContainerPortMundra": "Building_ContainerPort",
    "Building_ContainerPortPiraeus": "Building_ContainerPort",
    "Building_ContainerPortSantos": "Building_ContainerPort",
    "Building_ContainerPortTokyo": "Building_ContainerPort",
    "Building_ContainerPortGioiaTauro": "Building_ContainerPort",
    "Building_ContainerPortPortSaid": "Building_ContainerPort",
    "Building_ContainerPortFelixstowe": "Building_ContainerPort",
    "Building_ContainerPortVancouver": "Building_ContainerPort",
    "Building_ContainerPortAmbarli": "Building_ContainerPort",
    "Building_ContainerPortMelbourne": "Building_ContainerPort",

    // "Building_InterceptorMissileFactory": "Building_RocketFactory",
    // "Building_GuidedMissileFactory": "Building_RocketFactory",
    // "Building_CruiseMissileFactory": "Building_RocketFactory",
    // "Building_DroneFactory": "Building_RocketFactory",
    // "Building_CombatDroneFactory": "Building_RocketFactory",
    "Building_IronDome": "Building_RocketFactory",
    // "Building_ModernFighterFactory": "Building_FighterJetPlant",
    // "Building_StealthFighterFactory": "Building_FighterJetPlant",
    // "Building_StealthBomberFactory": "Building_FighterJetPlant",
    "Building_ModernAircraftCarrierYard": "Building_AircraftCarrierYard",
    "Building_ModernBattleshipYard": "Building_BattleshipBuilder",
    // "Building_MightMakesRight": "Building_NuclearMissileSilo",

    "Building_IndustrialWheatFarm": "Building_WheatFarm",
    "Building_TulipField": "Building_Floriculture",
    "Building_CocoaFarm": "Building_CocoaBean",
    "Building_CocoaPlantation": "Building_CocoaBean",
    "Building_SugarPlantation": "Building_SugarBeetFarm",
    "Building_DrinksMarket": "Building_Supermarket",
    "Building_Tenement": "Building_Condo",

    "Building_WorldChildrensDay": "Building_ChildrensDay",

    "Person_JanMarsalek": "Person_RobertNoyce",
    "Person_MarkusBraun": "Person_PhiloFarnsworth",
    "Person_Lydia": "Person_Dido",

    // Dutch:
    "Building_Headquarter_Dutch": "Building_Hermitage",
    // "Person_FlorisV": "Person_RabindranathTagore",
    "Person_JanVermeer": "Person_ChristopherColumbus",
    // "Person_VincentVanGogh": "Person_GeorgiusAgricola",
    "Person_MiguelIndurain": "Person_NielsBohr",
    // "Building_BicycleFactory": "Building_LocomotiveFactory",
    "Building_UtrechtDistrict": "Building_Villa",
    "Building_VanGoghMuseum": "Building_Museum",
    "Building_InternationalCriminalCourt": "Building_Courthouse",
    "Building_DeltaWorks": "Building_HydroDam",

    "Building_KotiRepository": "Building_WallStreet",
    "Building_NuclearWasteRepository": "Building_GrottaAzzurra",
}
//    "Person_MarkusBraun": "Person_EnricoFermi",
//    "Person_JanMarsalek": "Person_HarryMarkowitz",
//    "Person_MarkusBraun": "Person_HarryMarkowitz",

// export type TextureAlias = keyof TextureAliases;